{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v -}}
{{- $sa := $v.rbac.serviceAccount -}}

--- # --------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "common.fullname" . }}
  labels:
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $main.labels
                          $sa.labels ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $main.annotations
                          $sa.annotations ) ) | nindent 4 }}
{{- with $sa.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
