name: Garbage Collection

on:
  schedule:
    - cron: '0 0 */7 * *' 

jobs:
  garbage-collection:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete version via gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REGEX: '^mgr\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$'
        run: |
          gh api -H "Accept: application/vnd.github+json" /users/${{ github.repository_owner }}/packages/container/r8r/versions | \
            jq -r '.[] | select( (.metadata.container.tags // []) | map(select(test("$REGEX"))) | length == 0 ) | .id' | \
            while read -r id; do
              echo "Deleting package version $id"
              gh api --method DELETE -H "Accept: application/vnd.github+json" "/users/${{ github.repository_owner }}/packages/container/r8r/versions/$id"
            done
      #- name: Remove Images
      #  uses: actions/delete-package-versions@v5
      #  with: 
      #    token: ${{ secrets.GHP_TOKEN }}
      #    package-name: 'r8r'
      #    package-type: 'container'
      #    min-versions-to-keep: 0
      #    delete-only-untagged-versions: 'true'